project:
  type: website

website:
  title: "%>% dreams"
  site-url: https://ivelasq.rbind.io/
  description: "Isabella Velásquez Personal Website"
  favicon: logo.png
  twitter-card: 
    creator: "@ivelasq3"
  opengraph: true
  navbar:
    background: dark
    pinned: true
    right:
      - blog.qmd
      - talk.qmd
      - icon: twitter
        href: https://twitter.com/ivelasq3
      - icon: github
        href: https://github.com/ivelasq
      - icon: linkedin
        href: https://www.linkedin.com/in/ivelasq/
      - icon: rss
        href: index.xml
format:
  html:
    theme: [litera, styles.scss]