project:
  type: website
  resources:
    - "_redirects.txt"
    - "tweet-archive.html"
    - "nitter.css"
    - "twitter.css"
    - "fonts/css/fontello.css"
    - "fonts/font/fontello.ttf"
    - "fonts/font/fontello.woff"
    - "fonts/font/fontello.woff2"
    - "styles.css"
    - "js/vue.global.js"
    - "js/minisearch.min.js"
    - "profile.jpg"
    - "searchDocuments.js"
    - "app.js"
    - "tweets_media"
    
website:
  title: "%>% dreams"
  site-url: "https://ivelasq.rbind.io"
  description: "Isabella Velásquez Personal Website"
  favicon: favicon.jpg
  twitter-card: true
  open-graph: true
  navbar:
    title: "Isabella Velásquez"
    background: "#000000"
    foreground: "#FFFFFF"
    pinned: true
    left:
      - text: "pipe dreams"
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - file: talk.qmd
      - file: project.qmd
      - file: til.qmd
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with Quarto
    right: 
      - href: license.qmd
        text: License
      - icon: rss
        href: index.xml
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/ivelasq3.bsky.social
      - icon: github
        href: https://github.com/ivelasq
      - icon: linkedin
        href: https://www.linkedin.com/in/ivelasq/
      - icon: mastodon
        href: https://fosstodon.org/@ivelasq3
      - icon: twitter
        href: tweet-archive.html
      
format:
  html:
    theme: [litera, styles.scss]
    include-in-header: plausible.html
    highlight-style: nord
    
execute:
  freeze: auto