project:
  type: website
  resources:
    - "_redirects.txt"

website:
  title: "%>% dreams"
  site-url: "https://ivelasq.rbind.io"
  description: "Isabella Velásquez Personal Website"
  body-header: "plausible.html"
  favicon: favicon.jpg
  twitter-card: true
  opengraph: true
  navbar:
    background: dark
    pinned: true
    right:
      - blog.qmd
      - talk.qmd
      - project.qmd
      - icon: twitter
        href: https://twitter.com/ivelasq3
      - icon: github
        href: https://github.com/ivelasq
      - icon: linkedin
        href: https://www.linkedin.com/in/ivelasq/
      - icon: rss
        href: index.xml
  page-footer:
    left: 
      - href: license.qmd
        text: License
    right:
      - href: https://www.quarto.org
        text: Built with Quarto
format:
  html:
    theme: [litera, styles.scss]