project:
  type: website
  resources:
    - "_redirects.txt"

website:
  title: "%>% dreams"
  site-url: "https://ivelasq.rbind.io"
  description: "Isabella Velásquez Personal Website"
  favicon: favicon.jpg
  twitter-card: true
  open-graph: true
  navbar:
    title: "Isabella Velásquez"
    background: "#000000"
    foreground: "#FFFFFF"
    pinned: true
    left:
      - text: "pipe dreams"
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - file: talk.qmd
      - file: project.qmd
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with Quarto
    right: 
      - href: license.qmd
        text: License
      - icon: twitter
        href: https://twitter.com/ivelasq3
      - icon: github
        href: https://github.com/ivelasq
      - icon: linkedin
        href: https://www.linkedin.com/in/ivelasq/
      - icon: mastodon
        href: https://fosstodon.org/@ivelasq3
      - icon: rss
        href: index.xml
format:
  html:
    theme: [litera, styles.scss]
    include-in-header: plausible.html
    highlight-style: nord