project:
  type: website
  resources:
    - "_redirects.txt"

website:
  title: "%>% dreams"
  site-url: "https://ivelasq.rbind.io"
  description: "Isabella Velásquez Personal Website"
  favicon: favicon.jpg
  twitter-card: true
  opengraph: true
  navbar:
    title: "Isabella Velásquez"
    background: "#000000"
    foreground: "#FFFFFF"
    pinned: false
    left:
      - text: "pipe dreams"
    right:
      - icon: twitter
        href: https://twitter.com/ivelasq3
      - icon: github
        href: https://github.com/ivelasq
      - icon: linkedin
        href: https://www.linkedin.com/in/ivelasq/
      - icon: rss
        href: index.xml
  sidebar:
    alignment: right
    title: "Menu"
    style: "docked"
    pinned: false
    search: true
    background: "#2B2423"
    type: "dark"
    contents:
      - text: "About"
        file: about.qmd
      - section: "---"
      - file: index.qmd    
      - section: "---"
      - text: "TIL"
        file: til.qmd
      - section: "---"
      - talk.qmd
      - section: "---"
      - project.qmd
      - section: "---"
  page-footer:
    left: 
      - href: license.qmd
        text: License
    right:
      - href: https://www.quarto.org
        text: Built with Quarto
format:
  html:
    theme: [litera, styles.scss]
    include-in-header: plausible.html
    highlight-style: nord