baseURL: "https://ivelasq.rbind.io/"
languageCode: en-us
title: "%>% dreams"
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: Isabella Vel치squez - This is my personal website. Nothing here is endorsed by my employer or any organizations of which I am a part. Content on this site is provided under a Creative Commons (CC-BY) 4.0 license. You may re-use this content as long as you indicate my authorship and provide a link back to the original material. Source code of the site is provided under the MIT license and may be reused without restriction. Many thanks to Dr. Noam Ross for the language included here!
enableEmoji: yes
publishDir: docs  
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
params:
  author:
    description: Author
    name: Isabella Vel치squez
    thumbnail: /images/thumbnail.png
  description: Isabella Vel치squez
  index:
    alertbar: no
    mdtext: I am a data analyst working in philanthropy. Follow me on [Twitter](https://twitter.com/ivelasq3) for more updates. |
      [Resume](https://docs.google.com/document/d/14tJLqFuI9g6hDkP5IYQg0HPTZ05WVHxacedhajiilHo/edit?usp=sharing) | [R-Bloggers](https://www.r-bloggers.com/author/dreams/)
    picture: /images/author.png
    subtitle: "%>% dreams"
    title: Isabella Vel치squez
  logo: /images/logo.png
  social:
    github: ivelasq
    twitter: ivelasq3
    linkedin: ivelasq
menu:
  main:
    - identifier: about
      name: About Me
      url: /
      weight: 100
    - identifier: blog
      name: Blog
      url: /blog
      weight: 200
    - identifier: portfolio
      name: Portfolio
      url: /static/portfolio
      weight: 300

markup:
  goldmark:
    renderer:
      unsafe: true
