---
title: "Resume"
---

## Isabella Velásquez

ivelasq@gmail.com | 312-342-1122

### EDUCATION
THE UNIVERSITY OF CHICAGO 
MS Analytics, 2016
BA Double Major In Economics and East Asian Languages and Civilizations, 2010

### TECHNICAL SUMMARY
Analysis: R (Expert), Python (Beginner)
Version Control: Git (Proficient), GitHub (Proficient)
Visualization: R (Expert), Tableau (Proficient)
Mapping: R (Expert), QGIS (Beginner)

### PUBLICATION
Estrellado, R. A., Freer, E. A., Mostipak, J., Rosenberg, J. M., & Velásquez, I. C. (2020). Data science in education using R. London, England: Routledge. Nb. All authors contributed equally. Available at https://datascienceineducation.com/.

### EXPERIENCE
2021 – PRESENT, REMOTE
SR. PRODUCT MARKETING MANAGER, RSTUDIO
* Create written content to promote awareness of RStudio’s commercial products and overall brand
* Conduct data collection to evaluate viewership trends and develop marketing strategies
* Coordinate efforts across contributors to plan, edit, refine and stage content for blog posts, web pages
* Use data to identify gaps in our content and themes
* Develop long-term marketing plans and set achievable goals
2016 – 2021, SEATTLE, WA 
DATA ANALYST, BILL & MELINDA GATES FOUNDATION
* Design data infrastructure to organize, document, and track data (Google Sheets, MySQL, Airtable, internal CKAN data management system)
* Determine the appropriate analysis method and conduct descriptive and predictive analyses using R (exploratory data analysis using dplyr, tidytext, survey, mediation)
* Release reports and findings to make data and resources accessible, useful, and engaging to K-12 staff
* Create resources and trainings to engage technical and non-technical audiences in using education data
* Identify user needs through user research, analysis, and communication
* Design approaches to increase internal and external access and use of data and data exploration/synthesis tools
* Release outputs efficiently by applying agile principles and tracking using Jira
* Recognize and enable organic collaboration opportunities across individuals, teams, and organizations
* Convene and direct fellow analysts to answer research questions and develop resources
* Create striking visualizations, presentations, and memos using R (ggplot2, leaflet, likert)
* Develop repeatable processes and structures for regular analysis and reports (enterprise GitHub repository
    maintenance, internal R package creation and updates, R Markdown template design)
* Recognize and elevate patterns in equity-centered best practices across our work
2014 – 2016, CHICAGO, IL 
SURVEY SPECIALIST II, NORC AT THE UNIVERSITY OF CHICAGO 
* Provided operational and analytic support to the National Longitudinal Surveys of Youth team
* Designed resources and executed trainings for support staff
* Maintained central Access databases and wrote SQL for data queries
* Created digestible Tableau dashboards based on queries on a frequent basis
* Identified key factors for project completion goals, assessed performance of these factors, and provided recommendations to achieve targets
