---
title: "Talks and Workshops"
listing:
  contents:
    - "metadata.yml"
  type: grid
  date-format: "DD MMMM YYYY"
  fields: [date, title, event, recording, author, slides, extsite, repo]
  template: /talk/talk-listing.ejs
  sort: "date desc"
  feed: true
page-layout: full
format:
  html:
    css: /talk/talks.css
filters:
  - fontawesome
---

## Upcoming

### April 16 | The Invisible Work in Data Science Projects | Northern Illinois University | DeKalb, IL

What does it mean to work with tools, systems, and models that you didn't create yourself? I look forward to discussing with the students at Northern Illinois University's MIS and MSDA programs!

### April 22 | Working Smarter in R: Tips, Tricks & Real-World Lessons | R-Ladies Remote | Virtual

Nicola Rennie, Pao C., Meghan Harris, Soraya C., Crystal Lewis, and I will share tips on workflows, data cleaning, debugging and more in R! [Register for the panel here](https://www.meetup.com/rladies-remote/events/313908392/).

### April 29 | Getting Started with Quarto: A Hands-On Workshop | RNVSU | Virtual

I will join the R User Group at Nueva Vizcaya State University (RNVSU) for a virtual, hands-on intro workshop on Quarto. [Register for the workshop here](https://www.meetup.com/r-nvsu/events/313601010/?eventOrigin=group_upcoming_events).

### May 13 - 18 | PyCon US | Long Beach, CA

Come join me and other Posit folks at Booth #738! [Register for PyCon US here](https://us.pycon.org/2026/).

### June 16 | R/Pharma GenAI Day | Virtual

Thinking about boosting your skills in (LLM) skills? Join us to learn more! I'll add the link to register once it's available.

## Past

Subscribe to event recaps: <a href="https://ivelasq.rbind.io/talk.xml" target="_blank"><i class="fa-sharp fa-solid fa-rss"></i></a> {{< fa cat >}} 
