---
output:
  html_document:
    theme:
      version: 4
---

# Websites

```{r, echo = FALSE}
site2 <- bs4cards::card(
  title = "Data Science in Education Using R Website",
  image = "/images/sites/dsieur.png",
  text = "Bookdown site for Data Science in Education Using R.",
  link = "datascienceineducation.com/"
)

site1 <- bs4cards::card(
  title = "R-Ladies Seattle Website",
  image = "/images/sites/r-ladies-seattle.png",
  text = "Main site for the R-Ladies Seattle community.",
  link = "https://rladiesseattle.org/"
)

kitty_list <- list(
  site2, site1
)

bs4cards::card_grid(kitty_list)
```

# Apps

```{r, echo = FALSE}
app1 <- bs4cards::card(
  title = "Spurious Correlation Creator",
  image = "/images/sites/correlations.png",
  text = "A Shiny app for creating graphs of spurious correlations.",
  link = "https://ivelasq.shinyapps.io/SpuriousCOVIDCorrelationCreator/"
)

app2 <- bs4cards::card(
  title = "ganttrrr",
  image = "/images/sites/ganttrrr.png",
  text = "A Shiny app for creating Gantt charts using DiagrammeR::mermaid().",
  link = "https://ivelasq.shinyapps.io/ganttrrr/"
)


kitty_list <- list(
  app1,
  app2
)

bs4cards::card_grid(kitty_list)
```
